source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'


gem 'devise_token_auth'
gem 'omniauth'
gem 'active_model_serializers'
gem 'awesome_print' #better logging

gem 'rack-cors', :require => 'rack/cors'

gem 'rspec-rails', '~> 3.0'
gem 'factory_girl_rails'
