source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use sqlite3 as the database for Active Record
group :development do
  #gem 'sqlite3'
  gem 'mysql2'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
end


gem 'devise_token_auth'
gem 'omniauth'
gem 'active_model_serializers'
gem 'awesome_print' #better logging

gem 'rack-cors', :require => 'rack/cors'


group :development,:test do
  gem 'factory_girl_rails'
  gem 'faker'
end

group :test do
  gem 'database_cleaner'
  gem 'rspec-rails', '~> 3.0.0'
  gem 'shoulda-matchers' , require: false
  gem 'rspec-collection_matchers'
end
